import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  // ─── Ignore ──────────────────────────────────────────────────
  {
    ignores: [
      '.next/**',        // Next.js build output (webpack bundles, compiled JS)
      'node_modules/**', // Dependencies
      'out/**',          // Static export output
      'public/**',       // Static assets
      'next-env.d.ts',   // Auto-generated by Next.js — never edit manually
      'scripts/**',      // Plain Node.js utility scripts (CommonJS)
      '*.config.js',
      '*.config.mjs',
      '*.config.ts',
    ],
  },

  // ─── Next.js + TypeScript rules ─────────────────────────────
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  // ─── Custom overrides ────────────────────────────────────────
  {
    rules: {
      // any[] casts in db.ts are intentional
      '@typescript-eslint/no-explicit-any': 'warn',
      // Allow unused variables prefixed with _
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern:         '^_',
          varsIgnorePattern:         '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
]

export default eslintConfig
